#!/bin/bash
#SBATCH --job-name=residual.job
#SBATCH --partition=h200x4
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=4
#SBATCH --output=/lustre/nvwulf/scratch/pezeng/dev/rsp/slurm_outputs/residual.txt
#SBATCH --error=/lustre/nvwulf/scratch/pezeng/dev/rsp/slurm_outputs/residual_err.txt
#SBATCH --time=02:00:00

# Start timer
start_time=$(date +%s)
echo "Job started at $(date)"

source ~/miniconda3/etc/profile.d/conda.sh
conda activate rsp
/lustre/nvwulf/home/pezeng/miniconda3/envs/rsp/bin/python /lustre/nvwulf/scratch/pezeng/dev/rsp/src/train_attention_residual.py

# End timer and calculate duration
end_time=$(date +%s)
echo "Job ended at $(date)"
duration=$((end_time - start_time))
echo "Total job duration: $((duration / 3600)) hours, $(((duration % 3600) / 60)) minutes, $((duration % 60)) seconds"